<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- variabel definisjoner -->
  <xacro:property name="qubeWidth" value="0.5"/>
  <xacro:property name="qubeLength" value="0.5"/>
  <xacro:property name="qubeHeight" value="0.5"/>
  <xacro:property name="cylinderHeight" value="0.04"/>
  <xacro:property name="cylinderRadius" value="0.07"/>
  <xacro:property name="indicatorWidth" value="0.005"/>
  <xacro:property name="indicatorLength" value="0.14"/>
  <xacro:property name="indicatorHeight" value="0.001"/>
  <xacro:property name="sIndicatorL" value="0.07"/>
  <xacro:property name="sIndicatorW" value="0.005"/>
  <xacro:property name="sIndicatorH" value="0.001"/>

  <!-- farge variabler -->
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <xacro:macro name="qube">
    <link name = "base_link">
      <visual>
        <geometry>
          <box size ="${qubeWidth} ${qubeLength} ${qubeHeight}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <box size="${qubeWidth} ${qubeLength} ${qubeHeight}"/>
        </geometry>
      </collision>
    </link>

    <link name="redDisc">
      <visual>
        <geometry>
          <cylinder radius="${cylinderRadius}" length="${cylinderHeight}"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${cylinderRadius}" length="${cylinderHeight}"/>
        </geometry>
      </collision>
    </link>

    <link name="whiteIndicator">
      <visual>
        <geometry>
          <box size="${indicatorLength} ${indicatorHeight} ${indicatorWidth}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <box size="${indicatorLength}  ${indicatorHeight} ${indicatorWidth}"/>
        </geometry>
      </collision>
    </link>

    <link name="sIndicator">
      <visual>
        <geometry>
          <box size="${sIndicatorL} ${sIndicatorH} ${sIndicatorW}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <box size="${sIndicatorL} ${sIndicatorH} ${sIndicatorW}"/>
        </geometry>
      </collision>
    </link>

    <joint name="motor_joint" type="continuous">
      <parent link="base_link"/>
      <child link="redDisc"/>
      <origin xyz="0 0 ${qubeHeight/2 + cylinderHeight/2}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <joint name="disc_to_indicator" type="fixed">
      <parent link="redDisc"/>
      <child link="whiteIndicator"/>
      <origin xyz="0 0 ${cylinderHeight/2}" rpy="${pi/2} 0 0"/>
    </joint>


    <joint name="sIndicator2disc" type="fixed">
      <parent link="redDisc"/>
      <child link="sIndicator"/>
       <origin xyz="${cylinderRadius/2} 0 ${cylinderHeight/2}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>
</robot>